(ns typography.data)

(def scales
 {:minor-second (/ 16 15)
  :major-second (/ 9 8)
  :minor-third  (/ 6 5)
  :major-third  (/ 5 4)
  :perfect-fourth (/ 4 3)
  :aug-fourth (/ 1.411 1)
  :perfect-fifth (/ 3 2)
  :minor-sixth (/ 8 5)
  :golden (/ 1.61803 1)
  :major-sixth (/ 5 3)
  :minor-seventh (/ 16 9)
  :major-seventh (/ 15 8)
  :octave (/ 2 1)
  :major-tenth (/ 5 2)
  :major-eleventh (/ 8 3)
  :major-twelfth (/ 3 1)
  :double-octave (/ 4 1)})

(def base-font-size 18)
(def base-line-height 1.2)
(def scale-ratio (:perfect-fifth scales))
